"""criar a tabela de lojas

Revision ID: bca0b0c126a1
Revises: 
Create Date: 2026-09-27 18:07:23.582322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bca0b0c126a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lojas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('logradouro', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=8), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=60), nullable=True),
    sa.Column('cidade', sa.String(length=60), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('criada_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lojas_cnpj'), 'lojas', ['cnpj'], unique=True)
    op.create_index(op.f('ix_lojas_id'), 'lojas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lojas_id'), table_name='lojas')
    op.drop_index(op.f('ix_lojas_cnpj'), table_name='lojas')
    op.drop_table('lojas')
    # ### end Alembic commands ###
